name: Build YimMenuV2

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Configure with CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release -S . -B build -G Ninja

      - name: Build DLL
        run: cmake --build build --config Release --target YimMenuV2

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: YimMenuV2-DLL
          path: build/*.dll
